Revert "增加参数和返回值提示"  -- ts 编译有问题 2.9.2
lib/util/remoterHelper.ts(39,25): error TS2370: A rest parameter must be of an array type.
lib/util/remoterHelper.ts(39,34): error TS2304: Cannot find name 'Parameters'.
lib/util/remoterHelper.ts(41,32): error TS2370: A rest parameter must be of an array type.
lib/util/remoterHelper.ts(41,41): error TS2304: Cannot find name 'Parameters'.
lib/util/remoterHelper.ts(43,29): error TS2370: A rest parameter must be of an array type.
lib/util/remoterHelper.ts(43,38): error TS2304: Cannot find name 'Parameters'.

This reverts commit 1dda90879af9885a56c38bca561d7bf04f1b63f5.